# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty

before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install -y clang-3.8 cmake
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=clang++ .. && make
  - ./tmp
  - ./test_multivisitor
  
