# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty

before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install -y clang-3.8 gcc-6 libstdc++-6-dev cmake

env:
  - CXX=clang++-3.8
  - CXX=g++
  - CXX=g++-6

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX .. && make
  - ./tmp
  - ./test_multivisitor
  
