# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: c++

env:
  - BUILD_CXX=clang++-3.8
  - BUILD_CXX=g++-6
  - BUILD_CXX=g++-5

before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - if test "$BUILD_CXX" = "clang++-3.8"; then sudo apt-get install -y clang-3.8 libstdc++-6-dev; fi
  - if test "$BUILD_CXX" = "g++-5"; then sudo apt-get install -y g++-5 libstdc++-5-dev; fi
  - if test "$BUILD_CXX" = "g++-6"; then sudo apt-get install -y g++-6 libstdc++-6-dev; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$BUILD_CXX .. && make
  - ./tmp
  - ./test_multivisitor
  
